### ISSUE TITLE
去掉images的配置后无法获得正确的临时图片文件

### ISSUE THREAD

**Issue by wanxsb** [chuyun/taro-plugin-canvas#1]

**Comment by wanxsb** [comment]
![image](https://user-images.githubusercontent.com/1924449/54738505-8446a500-4bef-11e9-9b49-bab19da0651d.png)

**Comment by wanxsb** [comment]
图片Images部分的配置我已经去掉，所以downloadFiles是没有问题的

**Comment by chuyun** [comment]
> 图片Images部分的配置我已经去掉，所以downloadFiles是没有问题的

设置下不校验安全域名

**Comment by wanxsb** [comment]
我重新尝试了，发现问题出在配置上：你的项目里面如果去掉images相关配置或者images: []都无法正常渲染图片。按照原插件官方的文档应该是可选参数

![image](https://user-images.githubusercontent.com/1924449/54739274-7cd4cb00-4bf2-11e9-9d43-934e36f53026.png)

**Comment by chuyun** [comment]
> 我重新尝试了，发现问题出在配置上：你的项目里面如果去掉images相关配置或者images: []都无法正常渲染图片。按照原插件官方的文档应该是可选参数

好的，我看到这个问题了，晚点我看看

**Comment by chuyun** [comment]
麻烦升级到最新的 1.0.4 版本，问题已修复
