### ISSUE TITLE
pixelRatio导致的blocks组件宽度异常

### ISSUE THREAD

**Issue by AndroidMing** [chuyun/taro-plugin-canvas#12]
如题，设置pixelRatio: 2
1.config字段中的width和height 原本取了屏幕宽高，现在需要乘以pixelRatio值，才能正常显示，否则显示左上角1/4的图
2.blocks组件显示异常，width目测变成了2倍，height没问题 (略费解)

const PIXEL_RATIO_NUM = 2
const windowWidth = Taro.getSystemInfoSync().windowWidth
const windowHeight = Taro.getSystemInfoSync().windowHeight

posterConfig: {
        width: windowWidth * PIXEL_RATIO_NUM,
        height: windowHeight * PIXEL_RATIO_NUM,
        backgroundColor: '#FFFFFF',
        debug: false,
        pixelRatio: PIXEL_RATIO_NUM,
        blocks: [
         {
            width: windowWidth * 0.68,
            height: windowWidth * 0.1,
            x: 100,
            y: 200,
            backgroundColor: '#FFDF73',
            text:
            {
              text: inviteText,
              color: '#FFFFFF',
              fontSize: 18,
              textAlign: 'center',
            },
            zIndex: 12,
          }
        ],
      }
![ratio1](https://user-images.githubusercontent.com/1921280/64088762-95d2d200-cd75-11e9-8ce0-ade1fda3d0f6.png)
![ratio2](https://user-images.githubusercontent.com/1921280/64088764-98352c00-cd75-11e9-8bb0-8680d841e61f.png)

**Comment by qicmsg** [comment]
> 如题，设置pixelRatio: 2
> 1.config字段中的width和height 原本取了屏幕宽高，现在需要乘以pixelRatio值，才能正常显示，否则显示左上角1/4的图
> 2.blocks组件显示异常，width目测变成了2倍，height没问题 (略费解)
> 
> const PIXEL_RATIO_NUM = 2
> const windowWidth = Taro.getSystemInfoSync().windowWidth
> const windowHeight = Taro.getSystemInfoSync().windowHeight
> 
> posterConfig: {
> width: windowWidth * PIXEL_RATIO_NUM,
> height: windowHeight * PIXEL_RATIO_NUM,
> backgroundColor: '#FFFFFF',
> debug: false,
> pixelRatio: PIXEL_RATIO_NUM,
> blocks: [
> {
> width: windowWidth * 0.68,
> height: windowWidth * 0.1,
> x: 100,
> y: 200,
> backgroundColor: '#FFDF73',
> text:
> {
> text: inviteText,
> color: '#FFFFFF',
> fontSize: 18,
> textAlign: 'center',
> },
> zIndex: 12,
> }
> ],
> }
> ![ratio1](https://user-images.githubusercontent.com/1921280/64088762-95d2d200-cd75-11e9-8ce0-ade1fda3d0f6.png)
> ![ratio2](https://user-images.githubusercontent.com/1921280/64088764-98352c00-cd75-11e9-8bb0-8680d841e61f.png)

要处理两个地方：
1、把this.initCanvas()方法放到setState回调里。这样能解决pixelRatio: 2无效问题。
this.setState({
      pixelRatio: config.pixelRatio || 1,
    },()=>{
     //把this.initCanvas()方法放到setState回调里
      this.initCanvas()......
});

2、设置pixelRatio: 2后，多行字体会有问题
修改draw.js源码的_drawSingleText方法：
![image](https://user-images.githubusercontent.com/20200176/68084427-39248e00-fe70-11e9-8adf-178de3bb0ae0.png)

@chuyun 
  /**
   * @description px => rpx
   * @param { number } px - 需要转换的数值
   * @param { boolean} int - 是否为 int
   * @param { number } [factor = this.state.factor] - 转化因子
   * @returns { number }
   */
  toRpx = (px, int, factor = this.state.factor) => {
    if (int) {
      return parseInt(px / factor);
    }
    return px / factor;
  }
这个方法是不是有问题，如果factor为小数，转之后会放大。

**Comment by chuyun** [comment]
@qicmsg  factor 对应的是 px 和 rpx 的转换因子，以iphone6s 为例 1px = 2rpx ，转换因子为0.5 转换后是会变大的，另外项目再用ts重构，pixelRatio的问题会跟随下个版本发布
