### ISSUE TITLE
作组件使用时属性的传递

### ISSUE THREAD

**Issue by taleyoung** [chuyun/taro-plugin-canvas#2]
把下面的小demo作组件引用的时候，父组件通过props传递给组件 组件接收不到props？请问有这个问题吗？

**Comment by chuyun** [comment]
> 把下面的小demo作组件引用的时候，父组件通过props传递给组件 组件接收不到props？请问有这个问题吗？

克隆一下代码，看一下demo里面的具体实现,暂时没发现你这个问题

**Comment by keep2zero** [comment]
我这里也一样, 接收不到props属性

**Comment by taleyoung** [comment]
> 我这里也一样, 接收不到props属性

这个我已经解决了 不是作者插件的问题 是taro在使用组件的时候必须给组件属性定义defaultProps才能正常接收属性 （而且问题主要出在不给组件定义的时候 有时候能接收到属性有时候接收不到属性......）我是这么解决的 你可以试一下
