### ISSUE TITLE
当image的尺寸设置的比图片原尺寸小的时候，图片会显示中间的部分

### ISSUE THREAD

**Issue by taleyoung** [chuyun/taro-plugin-canvas#3]
当image的尺寸设置的比图片原尺寸小的时候，图片会显示中间的部分（也就是说原图片上下都会被截掉一部分，如下图所示，红色方框中就是被截掉的部分），这边的需求是做到原图片上面一定会显示，原图片下面超过image设置的尺寸可以被截掉，这个有没有办法解决呢？非常感谢！

**Comment by chuyun** [comment]
> 当image的尺寸设置的比图片原尺寸小的时候，图片会显示中间的部分（也就是说原图片上下都会被截掉一部分，如下图所示，红色方框中就是被截掉的部分），这边的需求是做到原图片上面一定会显示，原图片下面超过image设置的尺寸可以被截掉，这个有没有办法解决呢？非常感谢！

图呢？这边图片尺寸未知的话，超出会被裁剪的，不然图片会被压缩

**Comment by chuyun** [comment]
源图片的尺寸是固定的吧？

**Comment by taleyoung** [comment]
> 源图片的尺寸是固定的吧？

是的  非常感谢回复 原图片的尺寸是固定的 但是比较长  所以会被截掉一部分 下载下来的图片也是截掉之后的图片   这边想实现的是渲染数据到长图上 然后小程序上显示的效果是从原图片最上面开始显示 超过canvas的地方被隐藏掉 但是保存到手机之后是源文件的长图。  尝试了把原图片整体缩小 使得canvas可以完全显示原图片 但是因为图片太小了 数据没法渲染上去 而且下载之后的图片非常模糊

**Comment by chuyun** [comment]
> > 源图片的尺寸是固定的吧？
> 
> 是的 非常感谢回复 原图片的尺寸是固定的 但是比较长 所以会被截掉一部分 下载下来的图片也是截掉之后的图片 这边想实现的是渲染数据到长图上 然后小程序上显示的效果是从原图片最上面开始显示 超过canvas的地方被隐藏掉 但是保存到手机之后是源文件的长图。 尝试了把原图片整体缩小 使得canvas可以完全显示原图片 但是因为图片太小了 数据没法渲染上去 而且下载之后的图片非常模糊
<img width="703" alt="屏幕快照 2019-04-07 17 39 22" src="https://user-images.githubusercontent.com/19328403/55681705-21c60680-595c-11e9-8db4-aaeb494ff526.png">
<img width="745" alt="屏幕快照 2019-04-07 17 38 56" src="https://user-images.githubusercontent.com/19328403/55681706-27bbe780-595c-11e9-95e7-e560c8d48de9.png">
这两个地方的height的配置修改下

**Comment by chuyun** [comment]
也可以发下配置看看
