### ISSUE TITLE
import { TaroCanvasDrawer } from "taro-plugin-canvas"导入的时候提示

### ISSUE THREAD

**Issue by youtingkun** [chuyun/taro-plugin-canvas#32]
无法找到模块“taro-plugin-canvas”的声明文件。“e:/demo/node_modules/taro-plugin-canvas/dist/index.js”隐式拥有 "any" 类型。
  Try `npm install @types/taro-plugin-canvas` if it exists or add a new declaration (.d.ts) file containing `declare module 'taro-plugin-canvas';`

**Comment by FinchJohnRen** [comment]
同问题， yarn 安装了node module文件夹里毛都没有啊
