### ISSUE TITLE
The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by laborclx** [chuyun/taro-plugin-canvas#39]
升级到1.0.9，编译失败，提示：The "path" argument must be of type string. Received type object

**Comment by MichaelHao25** [comment]
import { CanvasDrawer  } from 'taro-plugin-canvas';
改成这样即可 全局替换一下

**Comment by towry** [comment]
建议 postinstall 脚本里增加更新提示。

**Comment by chuyun** [comment]
```
import { CanvasDrawer } from 'taro-plugin-canvas';
```
