### ISSUE TITLE
reademe里npm标志改成这样的更markdown

### ISSUE THREAD

**Issue by honlyHuang** [chuyun/taro-plugin-canvas#5]
`[![npm](https://img.shields.io/npm/v/taro-plugin-canvas.svg?style=flat "npm")](https://www.npmjs.com/package/taro-plugin-canvas)[![npm](https://img.shields.io/npm/dm/taro-plugin-canvas.svg?style=flat "npm")](https://www.npmjs.com/package/taro-plugin-canvas)`

**Comment by chuyun** [comment]
好的，感谢
