### ISSUE TITLE
图片不支持base64

### ISSUE THREAD

**Issue by Drckk** [chuyun/taro-plugin-canvas#7]

**Comment by chuyun** [comment]
暂时不支持，后期会支持

**Comment by kmvan** [comment]
b64可以手动搞成文件然后再载入。

**Comment by qicmsg** [comment]
> b64可以手动搞成文件然后再载入。

你是怎样弄的？能回下代码吗？const fsm = wx.getFileSystemManager();
        fsm.writeFile  写入的临时路径是http的，无法识别

**Comment by DestinyMajesty** [comment]
base64的数据可以手动存入本地，然后再载入，我这里是用的taro的，代码如下：
async function test () {
    const base64img = 'xxxx';  // 以 data:image/png;base64, 开头的base64数据；
    const path= await base64Tosrc(base64img );
     // 这个path就可以用了
}

 function base64Tosrc (base64data) {
        const fsm = Taro.getFileSystemManager();
        const FILE_BASE_NAME = 'tmp_base64src';
	return new Promise((resolve, reject) => {
	  const [, format, bodyData] = /data:image\/(\w+);base64,(.*)/.exec(base64data) || [];
	  if (!format) {
			reject(new Error('ERROR_BASE64SRC_PARSE'));
	  }
	  const filePath = `${Taro.env.USER_DATA_PATH}/${FILE_BASE_NAME}.${format}`;
	  const buffer = Taro.base64ToArrayBuffer(bodyData);
	  fsm.writeFile({
			filePath,
			data: buffer,
			encoding: 'binary',
			success() {
				Taro.getImageInfo({
					src: filePath,
					success(res){
						resolve(res.path)
					},
				})
			},
			fail() {
		  		reject(new Error('ERROR_BASE64SRC_WRITE'));
			},
	  });
	});
};

**Comment by CourieLiu** [comment]
> ### base64的数据可以手动存入本地，然后再载入，我这里是用的taro框架的示例，代码如下：
> ```
> async function test () {
>     const base64img = 'xxxx';  // 以 data:image/png;base64, 开头的base64数据；
>     const path= await base64Tosrc(base64img );
>      // 这个path就可以用了
> ｝
> 
> function base64Tosrc (base64data) {
>         const fsm = Taro.getFileSystemManager();
>         const FILE_BASE_NAME = 'tmp_base64src';
> 	return new Promise((resolve, reject) => {
> 	  const [, format, bodyData] = /data:image\/(\w+);base64,(.*)/.exec(base64data) || [];
> 	  if (!format) {
> 			reject(new Error('ERROR_BASE64SRC_PARSE'));
> 	  }
> 	  const filePath = `${Taro.env.USER_DATA_PATH}/${FILE_BASE_NAME}.${format}`;
> 	  const buffer = Taro.base64ToArrayBuffer(bodyData);
> 	  fsm.writeFile({
> 			filePath,
> 			data: buffer,
> 			encoding: 'binary',
> 			success() {
> 				Taro.getImageInfo({
> 					src: filePath,
> 					success(res){
> 						resolve(res.path)
> 					},
> 				})
> 			},
> 			fail() {
> 		  		reject(new Error('ERROR_BASE64SRC_WRITE'));
> 			},
> 	  });
> 	});
> };
> ```

小程序能使用的缓存空间有限，所以最好在存储之前清理一下之前保存的内容
