### ISSUE TITLE
异步生成海报

### ISSUE THREAD

**Issue by liudake** [chuyun/taro-plugin-canvas#8]
有些场景可能需要发起ajax请求后才能获取生成海报的数据，需要引入或者配置那些操作。

**Comment by chuyun** [comment]
Ajax请求后获取配置后再将配置传进去就好了

**Comment by towry** [comment]
能否可以自定义 loading 文本。

**Comment by chuyun** [comment]
> 能否可以自定义 loading 文本。

哪个地方的loading文本

**Comment by towry** [comment]
https://github.com/chuyun/taro-plugin-canvas/blob/master/src/component/taro-plugin-canvas/index.js#L154

**Comment by chuyun** [comment]
> https://github.com/chuyun/taro-plugin-canvas/blob/master/src/component/taro-plugin-canvas/index.js#L154

暂时不支持，晚点支持下，你可以自己改下
