### ISSUE TITLE
lineNum: 2不起作用

### ISSUE THREAD

**Issue by FionaCY** [chuyun/taro-plugin-canvas#89]
<img width="259" alt="截屏2023-02-15 19 11 21" src="https://user-images.githubusercontent.com/28498973/219011843-e6c3ebe8-f46b-4da9-9626-9f67e60958de.png">
<img width="259" alt="截屏2023-02-15 19 11 21" src="https://user-images.githubusercontent.com/28498973/219011909-c2846f85-1ad1-41b1-ad48-67fff804d451.png">

麻烦帮忙看一下该咋处理，非常感谢！

**Comment by chuyun** [comment]
> <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011843-e6c3ebe8-f46b-4da9-9626-9f67e60958de.png">
> 
> <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011909-c2846f85-1ad1-41b1-ad48-67fff804d451.png">
> 
> 麻烦帮忙看一下该咋处理，非常感谢！

width: xxx

**Comment by FionaCY** [comment]
为啥关了啊？ 这个该咋解决啊

**Comment by FionaCY** [comment]
> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011843-e6c3ebe8-f46b-4da9-9626-9f67e60958de.png">
> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011909-c2846f85-1ad1-41b1-ad48-67fff804d451.png">
> > 麻烦帮忙看一下该咋处理，非常感谢！
> 
> width: xxx



> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011843-e6c3ebe8-f46b-4da9-9626-9f67e60958de.png">
> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011909-c2846f85-1ad1-41b1-ad48-67fff804d451.png">
> > 麻烦帮忙看一下该咋处理，非常感谢！
> 
> width: xxx

请问一下为啥这里设置了width不起作用
<img width="257" alt="截屏2023-02-16 10 18 32" src="https://user-images.githubusercontent.com/28498973/219250945-86520862-d556-4088-af73-178024743e7e.png">

**Comment by FionaCY** [comment]
> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011843-e6c3ebe8-f46b-4da9-9626-9f67e60958de.png">
> > <img alt="截屏2023-02-15 19 11 21" width="259" src="https://user-images.githubusercontent.com/28498973/219011909-c2846f85-1ad1-41b1-ad48-67fff804d451.png">
> > 麻烦帮忙看一下该咋处理，非常感谢！
> 
> width: xxx

<img width="247" alt="截屏2023-02-16 10 20 09" src="https://user-images.githubusercontent.com/28498973/219251178-e1670f27-7332-42a1-ad56-073e215f1c01.png">
<img width="547" alt="截屏2023-02-16 10 21 09" src="https://user-images.githubusercontent.com/28498973/219251222-53cba362-a8f8-4e41-b670-0e3c0cd32de3.png">
为啥这里设置width 不起作用啊
